<a href="https://colab.research.google.com/github/alejobeni91123/Entregable-BIT-Alejandro-barrios/blob/master/02_Python/Clase_08_Taller_Pandas_%26_NumPy_Cafe_Sales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Taller práctico: Limpieza de datos con Pandas + NumPy


**Dataset:** Dirty Cafe Sales  


## Reto

Una cafetería nos entregó su historial de transacciones, pero la base contiene datos faltantes, valores inválidos, tipos incorrectos y registros duplicados.

Tu misión es:

**diagnosticar → limpiar → transformar → validar**

Al finalizar, queremos conseguir un DataFrame completamente limpio:

```python
df.isna().sum().sum()
```

debe devolver:

```text
0
```

> **Importante:** no vamos a aplicar la misma solución a todas las columnas. Tendrás que decidir qué estrategia corresponde a cada problema.

In [1]:
import pandas as pd
import numpy as np

## 0. Preparación

Vamos a trabajar directamente con el archivo desde una URL, así todos utilizaremos la misma fuente de datos.

Ejecuta la siguiente celda.

In [3]:
url = "https://raw.githubusercontent.com/shaadyalii/Dirty-Cafe-Sales-Dataset/main/dirty_cafe_sales.csv"

df = pd.read_csv(url)

df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

## 1. Diagnóstico inicial

### Pregunta 1

Cuántas filas y columnas tiene el DataFrame?

In [4]:
# Tu código aquí
df.shape

(10000, 8)

### Pregunta 2

Muestra:

- los nombres de las columnas
- los tipos de datos
- información general del DataFrame

Puedes utilizar `columns` e `info()`.

In [6]:
# Tu código aquí
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

### Pregunta 3

Cuántos valores nulos tiene cada columna?

Recuerda que `isna()` identifica valores ausentes.

In [7]:
# Tu código aquí
df.isna().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

### Pregunta 4

Cuántos registros duplicados existen?

In [14]:
# Tu código aquí
df.duplicated().sum()

np.int64(0)

## 2. Detectar valores inválidos

Un dato problemático no siempre aparece como `NaN`.

En esta base también podemos encontrar valores como:

```text
ERROR
UNKNOWN
```

### Pregunta 5

Busca en qué columnas aparecen estos valores y cuántos hay.

In [27]:
for col in df.columns:
  error = df[col].isin(["ERROR", "UNKNOWN"]).sum()
  if error > 0:
    print(col,error)

Item 636
Quantity 341
Price Per Unit 354
Total Spent 329
Payment Method 599
Location 696
Transaction Date 301

### Pregunta 6

Reemplaza `ERROR` y `UNKNOWN` por `np.nan`.

In [29]:
# Tu código aquí
df = df.replace(["ERROR","UNKNOWN"] np.nan)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3769118649.py, line 2)

### Pregunta 7

Después de reemplazar los valores inválidos, vuelve a revisar los valores nulos.

Aumentó el número de valores faltantes? Por qué?

In [24]:
# Tu código aquí
df.isna().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [20]:
# Tu código aquí

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

## 3. Eliminar duplicados

### Pregunta 8

Elimina los registros duplicados.

In [31]:
# Tu código aquí
filas_originales = len(df)
df = df.drop_duplicates()
filas_sin_duplicados = len(df)
print(f"Filas originales: {filas_originales}")
print(f"Filas sin duplicados: {filas_sin_duplicados}")
print (filas_originales - filas_sin_duplicados)

Filas originales: 10000
Filas sin duplicados: 10000
0

## 4. Conversión de tipos

### Pregunta 9

Convierte estas columnas a numéricas:

- `Quantity`
- `Price Per Unit`
- `Total Spent`

**Pista:**

```python
pd.to_numeric()
```

y utiliza `errors="coerce"`.

In [37]:
# Tu código aquí
columnas_numericas = ("Quantity", "Price Per Unit", "Total Spent")
for col in columnas_numericas:
  df[col] = pd.to_numeric(df[col], errors = "coerce")
df[columnas_numericas].dtypes

KeyError: ('Quantity', 'Price Per Unit', 'Total Spent')

### Pregunta 10

Convierte `Transaction Date` a formato fecha.

**Pista:**

```python
pd.to_datetime()
```

In [42]:
# Tu código aquí
df["Transaction Date"] = pd.to_datetime(df["Transaction Date"], errors = "coerce")
df["Transaction Date"].dtypes

dtype('<M8[ns]')

### Pregunta 11

Comprueba que las conversiones funcionaron correctamente.

Qué tipo de dato tiene ahora cada columna?

In [44]:
# Tu código aquí
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9521 non-null   float64
 3   Price Per Unit    9467 non-null   float64
 4   Total Spent       9498 non-null   float64
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9540 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(3), object(4)
memory usage: 625.1+ KB

## 5. Tratamiento de valores faltantes

Ahora tenemos que tomar decisiones.

Utilizaremos diferentes estrategias:

| Columna | Estrategia |
|---|---|
| `Item` | `"Unknown"` |
| `Quantity` | Mediana |
| `Price Per Unit` | Mediana |
| `Total Spent` | Recalcular |
| `Payment Method` | Moda |
| `Location` | Moda |
| `Transaction Date` | Fecha mediana |

### Pregunta 12 — `Item`

Tenemos transacciones donde no sabemos qué producto fue vendido.

Sería correcto reemplazar todos los faltantes por el producto más frecuente?

### Pregunta 12

Completa los valores faltantes de `Item` utilizando:

```text
Unknown
```

In [45]:
# Tu código aquí
df["Item"] = df["Item"].fillna("Unknown")
df["Item"].isna().sum()

np.int64(0)

## 6. NumPy: mediana de `Quantity`

### Pregunta 13

Calcula la mediana de `Quantity` **ignorando los valores nulos**.

Busca una función de NumPy que empiece por:

```python
np.nan...
```

In [46]:
# Tu código aquí
mediana_cantidad = np.nanmedian(df["Quantity"])
mediana_cantidad

np.float64(3.0)

### Pregunta 14

Utiliza la mediana calculada para completar los valores faltantes de `Quantity`.

Después comprueba que ya no existan valores nulos en esa columna.

In [47]:
# Tu código aquí
df["Quantity"] = df["Quantity"].fillna(mediana_cantidad)
df["Quantity"].isna().sum()

np.int64(0)

## 7. `Price Per Unit`

### Pregunta 15

Calcula la mediana de `Price Per Unit` utilizando NumPy y úsala para completar cualquier valor faltante.

In [51]:
# Tu código aquí
mediana_cantidad = np.nanmedian(df["Price Per Unit"])
mediana_cantidad

np.float64(3.0)

In [52]:
df["Price Per Unit"] = df["Price Per Unit"].fillna(mediana_cantidad)
df["Price Per Unit"].isna().sum()

np.int64(0)

## 8. Reconstruir `Total Spent`

Esta vez **no vamos a utilizar la mediana**.

Observa las columnas:

```text
Quantity
Price Per Unit
Total Spent
```

Existe una relación entre ellas:

```text
Total Spent = Quantity × Price Per Unit
```

### Pregunta 16

Utiliza esa relación para reconstruir `Total Spent`.

In [53]:
# Tu código aquí
df["Total Spent"] = (df["Quantity"] * df["Price Per Unit"])
df["Total Spent"].isna().sum()

np.int64(0)

## 9. Variables categóricas

`Payment Method` y `Location` son variables categóricas.

### Pregunta 17

Si todavía existen valores nulos en estas columnas:

1. Calcula la moda.
2. Utiliza la moda para completar los valores faltantes.
3. Comprueba el resultado.

Puedes utilizar un `for` para resolver ambas columnas.

In [59]:
for col in ["Payment Method", "Location"]:
  if df[col].isna().any():
    moda = df[col].mode()[0]
    df[col] = df[col].fillna(moda)
print(df[["Payment Method", "Location"]].isna().sum())

Payment Method    0
Location          0
dtype: int64

## 10. `Transaction Date`

Tenemos valores faltantes en la fecha de transacción.


### Pregunta 18

Calcula una fecha representativa utilizando la fecha central de los registros disponibles y úsala para completar los valores faltantes.

Pista:

1. Elimina temporalmente los `NaT`.
2. Ordena las fechas.
3. Obtén el valor central.
4. Usa `fillna()`.

In [ ]:
# Tu código aquí

## 11. Crear `Revenue_Calculated`

Ahora que las variables necesarias están limpias, podemos crear una nueva variable.

### Pregunta 19

Calcula:

```text
Revenue = Quantity × Price Per Unit
```

y guarda el resultado en:

```text
Revenue_Calculated
```

In [ ]:
# Tu código aquí

### Pregunta 20

Comprueba si `Revenue_Calculated` contiene valores nulos.

In [ ]:
# Tu código aquí

## 12. `np.where()`

NumPy para crear una clasificación.

### Pregunta 21

Crea una columna llamada `Revenue_Level` con estas reglas:

- `High` si `Revenue_Calculated >= 15`
- `Low` si `Revenue_Calculated < 15`

Utiliza `np.where()`.

La estructura general es:

```python
np.where(condición, valor_si_se_cumple, valor_si_no_se_cumple)
```

In [ ]:
# Tu código aquí

## 13. Validación de la limpieza

### Pregunta 22

Cuántos valores nulos quedan en cada columna?

In [ ]:
# Tu código aquí

## Reto final

Ahora que la base está limpia, responde estas preguntas utilizando código.

### 1. ¿Cuál es el producto con mayor cantidad vendida?

### 2. ¿Qué producto genera mayor revenue?


**Pista:** Utiliza la herramienta: `groupby()`

In [ ]:
# Tu código aquí